#!/usr/bin/env bash
set -euo pipefail

main() {
	local filepath="$1"
	local filename="${filepath##*/}"
	if [[ "$filename" == index.md ]]; then
		filename="${filepath%/*}"
		filename="${filename##*/}"
	fi
	local slug="${filename%.*}"

	local headrev tailrev writtenAt updatedAt
	headrev=$(commit "$filepath")
	tailrev=$(commit "$filepath" --reverse)
	if [[ -n "$tailrev" ]]; then
		writtenAt=$(commit_date "$tailrev")
	fi
	if [[ -n "$headrev" ]]; then
		updatedAt=$(commit_date "$headrev")
	fi

	if [[ "$slug" =~ ^[0-9]*\+ ]]; then
		writtenAt="${slug%%+*}"
		slug="${slug#*+}"
	fi

	if [[ -z "$updatedAt" ]] || ! git diff --exit-code --quiet "$filepath"; then
		read -r updatedAt < <(stat -c '%Y' "$filepath")
	fi

	if [[ -z "$writtenAt" ]]; then
		writtenAt="$updatedAt"
	fi

	echo "$writtenAt" "$updatedAt" "$slug"
}

commit() {
	git log --oneline "${@:2}" "$1" | head -n1 | cut -f1 -d' ' 2> /dev/null
}

commit_date() {
	git show -s --format="%cd" --date="format:%s" "$1"
}

main "$@"
