#!/usr/bin/env bash
set -euo pipefail

main() {
	if (( $# != 1 )); then
		echo "Usage: $0 <file>" >&2
		return 1
	fi

	if [[ ! -f "$1" ]]; then
		echo "Error: File not found: $1" >&2
		return 1
	fi

	local threshold=400
	local synopsis=
	local index=0
	local html
	html=$(cmark --nobreaks "$1")

	while true; do
		((++index))
		local newElement
		newElement=$(htmlq "body > *:nth-child(${index})" <<< "${html}" || true)
		if [[ -z "$newElement" ]]; then
			break
		fi
		local newSynopsis=$synopsis
		newSynopsis+="$newElement"
		newSynopsis+=$'\n'
		if (( ${#synopsis} > 0 && ${#newSynopsis} > threshold )); then
			break
		fi
		if [[ "$newSynopsis" =~ ^.*\<h[2-6]\>.*$ ]]; then
			break
		fi
		synopsis=$newSynopsis
	done

	echo -n "$synopsis"
}

main "$@"
